interface CityEntry {
  name: string;
  country: string;
  rank: number;
}

// This is a much larger database of cities with country codes to simulate API-like responses
// In a production app, you would use a service like Google Places API for real dynamic suggestions
export const cityDatabase: CityEntry[] = [
  // Major world cities
  { name: "London", country: "GB", rank: 100 },
  { name: "New York", country: "US", rank: 100 },
  { name: "Tokyo", country: "JP", rank: 100 },
  { name: "Paris", country: "FR", rank: 100 },
  { name: "Sydney", country: "AU", rank: 95 },
  { name: "Berlin", country: "DE", rank: 95 },
  { name: "Rome", country: "IT", rank: 95 },
  { name: "Dubai", country: "AE", rank: 95 },
  { name: "Toronto", country: "CA", rank: 95 },
  { name: "Singapore", country: "SG", rank: 95 },
  { name: "Hong Kong", country: "HK", rank: 95 },
  { name: "Los Angeles", country: "US", rank: 95 },
  { name: "Cairo", country: "EG", rank: 90 },
  { name: "Mumbai", country: "IN", rank: 90 },
  { name: "Rio de Janeiro", country: "BR", rank: 90 },

  // Diverse global cities (alphabetical) - larger dataset
  { name: "Aachen", country: "DE", rank: 60 },
  { name: "Aalborg", country: "DK", rank: 60 },
  { name: "Aberdeen", country: "GB", rank: 70 },
  { name: "Abu Dhabi", country: "AE", rank: 85 },
  { name: "Acapulco", country: "MX", rank: 75 },
  { name: "Accra", country: "GH", rank: 75 },
  { name: "Adana", country: "TR", rank: 65 },
  { name: "Adelaide", country: "AU", rank: 80 },
  { name: "Agra", country: "IN", rank: 70 },
  { name: "Ahmedabad", country: "IN", rank: 75 },
  { name: "Albuquerque", country: "US", rank: 70 },
  { name: "Alexandria", country: "EG", rank: 80 },
  { name: "Algiers", country: "DZ", rank: 75 },
  { name: "Amman", country: "JO", rank: 75 },
  { name: "Amsterdam", country: "NL", rank: 90 },
  { name: "Anchorage", country: "US", rank: 65 },
  { name: "Ankara", country: "TR", rank: 80 },
  { name: "Antalya", country: "TR", rank: 75 },
  { name: "Antwerp", country: "BE", rank: 75 },
  { name: "Aswan", country: "EG", rank: 65 },
  { name: "Athens", country: "GR", rank: 85 },
  { name: "Atlanta", country: "US", rank: 80 },
  { name: "Auckland", country: "NZ", rank: 80 },
  { name: "Austin", country: "US", rank: 80 },

  // B cities
  { name: "Baghdad", country: "IQ", rank: 75 },
  { name: "Baku", country: "AZ", rank: 70 },
  { name: "Baltimore", country: "US", rank: 75 },
  { name: "Bangalore", country: "IN", rank: 85 },
  { name: "Bangkok", country: "TH", rank: 90 },
  { name: "Barcelona", country: "ES", rank: 90 },
  { name: "Basel", country: "CH", rank: 70 },
  { name: "Beijing", country: "CN", rank: 95 },
  { name: "Beirut", country: "LB", rank: 75 },
  { name: "Belfast", country: "GB", rank: 75 },
  { name: "Belgrade", country: "RS", rank: 75 },
  { name: "Belize City", country: "BZ", rank: 65 },
  { name: "Bergen", country: "NO", rank: 70 },
  { name: "Berlin", country: "DE", rank: 90 },
  { name: "Bern", country: "CH", rank: 75 },
  { name: "Bilbao", country: "ES", rank: 75 },
  { name: "Birmingham", country: "GB", rank: 80 },
  { name: "Bogota", country: "CO", rank: 85 },
  { name: "Bordeaux", country: "FR", rank: 75 },
  { name: "Boston", country: "US", rank: 85 },
  { name: "Boulder", country: "US", rank: 65 },
  { name: "Brasilia", country: "BR", rank: 80 },
  { name: "Bratislava", country: "SK", rank: 75 },
  { name: "Brazzaville", country: "CG", rank: 65 },
  { name: "Brighton", country: "GB", rank: 70 },
  { name: "Brisbane", country: "AU", rank: 80 },
  { name: "Bristol", country: "GB", rank: 75 },
  { name: "Brussels", country: "BE", rank: 85 },
  { name: "Bucharest", country: "RO", rank: 80 },
  { name: "Budapest", country: "HU", rank: 85 },
  { name: "Buenos Aires", country: "AR", rank: 90 },
  { name: "Buffalo", country: "US", rank: 65 },
  { name: "Bursa", country: "TR", rank: 65 },

  // C cities
  { name: "Cagliari", country: "IT", rank: 65 },
  { name: "Cairo", country: "EG", rank: 90 },
  { name: "Calgary", country: "CA", rank: 80 },
  { name: "Canberra", country: "AU", rank: 75 },
  { name: "Cape Town", country: "ZA", rank: 85 },
  { name: "Caracas", country: "VE", rank: 75 },
  { name: "Cardiff", country: "GB", rank: 75 },
  { name: "Casablanca", country: "MA", rank: 80 },
  { name: "Chengdu", country: "CN", rank: 80 },
  { name: "Chennai", country: "IN", rank: 85 },
  { name: "Chicago", country: "US", rank: 90 },
  { name: "Chiang Mai", country: "TH", rank: 75 },
  { name: "Christchurch", country: "NZ", rank: 75 },
  { name: "Cincinnati", country: "US", rank: 70 },
  { name: "Cleveland", country: "US", rank: 70 },
  { name: "Cologne", country: "DE", rank: 80 },
  { name: "Colombo", country: "LK", rank: 75 },
  { name: "Copenhagen", country: "DK", rank: 85 },
  { name: "Cork", country: "IE", rank: 70 },
  { name: "Curitiba", country: "BR", rank: 75 },

  // D cities
  { name: "Dakar", country: "SN", rank: 70 },
  { name: "Dallas", country: "US", rank: 85 },
  { name: "Damascus", country: "SY", rank: 70 },
  { name: "Dar es Salaam", country: "TZ", rank: 70 },
  { name: "Darwin", country: "AU", rank: 65 },
  { name: "Delhi", country: "IN", rank: 90 },
  { name: "Denver", country: "US", rank: 80 },
  { name: "Detroit", country: "US", rank: 75 },
  { name: "Dhaka", country: "BD", rank: 85 },
  { name: "Doha", country: "QA", rank: 85 },
  { name: "Dresden", country: "DE", rank: 75 },
  { name: "Dubai", country: "AE", rank: 95 },
  { name: "Dublin", country: "IE", rank: 85 },
  { name: "Dubrovnik", country: "HR", rank: 75 },
  { name: "Dundee", country: "GB", rank: 65 },
  { name: "Durban", country: "ZA", rank: 75 },
  { name: "Dusseldorf", country: "DE", rank: 80 },

  // E cities
  { name: "Edinburgh", country: "GB", rank: 85 },
  { name: "Edmonton", country: "CA", rank: 75 },
  { name: "Eindhoven", country: "NL", rank: 70 },

  // F cities
  { name: "Florence", country: "IT", rank: 85 },
  { name: "Frankfurt", country: "DE", rank: 85 },
  { name: "Freiburg", country: "DE", rank: 70 },
  { name: "Fukuoka", country: "JP", rank: 75 },

  // G cities
  { name: "Galway", country: "IE", rank: 70 },
  { name: "Gaborone", country: "BW", rank: 65 },
  { name: "Gdansk", country: "PL", rank: 70 },
  { name: "Geneva", country: "CH", rank: 85 },
  { name: "Genoa", country: "IT", rank: 75 },
  { name: "Georgetown", country: "GY", rank: 65 },
  { name: "Glasgow", country: "GB", rank: 80 },
  { name: "Gothenburg", country: "SE", rank: 75 },
  { name: "Granada", country: "ES", rank: 75 },
  { name: "Guangzhou", country: "CN", rank: 85 },

  // H cities
  { name: "Hague", country: "NL", rank: 80 },
  { name: "Hamburg", country: "DE", rank: 85 },
  { name: "Hanoi", country: "VN", rank: 85 },
  { name: "Havana", country: "CU", rank: 80 },
  { name: "Helsinki", country: "FI", rank: 85 },
  { name: "Ho Chi Minh City", country: "VN", rank: 85 },
  { name: "Hong Kong", country: "HK", rank: 95 },
  { name: "Honolulu", country: "US", rank: 80 },
  { name: "Houston", country: "US", rank: 85 },
  { name: "Hyderabad", country: "IN", rank: 80 },

  // I cities
  { name: "Indianapolis", country: "US", rank: 75 },
  { name: "Innsbruck", country: "AT", rank: 70 },
  { name: "Istanbul", country: "TR", rank: 90 },
  { name: "Izmir", country: "TR", rank: 75 },

  // J cities
  { name: "Jakarta", country: "ID", rank: 90 },
  { name: "Jerusalem", country: "IL", rank: 85 },
  { name: "Johannesburg", country: "ZA", rank: 85 },

  // K cities
  { name: "Kampala", country: "UG", rank: 70 },
  { name: "Kansas City", country: "US", rank: 75 },
  { name: "Karachi", country: "PK", rank: 85 },
  { name: "Kathmandu", country: "NP", rank: 75 },
  { name: "Kiev", country: "UA", rank: 80 },
  { name: "Kigali", country: "RW", rank: 65 },
  { name: "Kingston", country: "JM", rank: 70 },
  { name: "Kobe", country: "JP", rank: 75 },
  { name: "Kolkata", country: "IN", rank: 85 },
  { name: "Krakow", country: "PL", rank: 80 },
  { name: "Kuala Lumpur", country: "MY", rank: 85 },
  { name: "Kyoto", country: "JP", rank: 85 },

  // More diverse global locations to simulate API
  { name: "Manhattan", country: "US", rank: 85 },
  { name: "Marrakech", country: "MA", rank: 80 },
  { name: "Monaco", country: "MC", rank: 75 },
  { name: "Nashville", country: "US", rank: 75 },
  { name: "Naples", country: "IT", rank: 80 },
  { name: "Nice", country: "FR", rank: 80 },
  { name: "Nuremberg", country: "DE", rank: 75 },
  { name: "Oaxaca", country: "MX", rank: 70 },
  { name: "Orlando", country: "US", rank: 80 },
  { name: "Osaka", country: "JP", rank: 85 },
  { name: "Oslo", country: "NO", rank: 85 },
  { name: "Oxford", country: "GB", rank: 80 },
  { name: "Phuket", country: "TH", rank: 80 },
  { name: "Pittsburgh", country: "US", rank: 75 },
  { name: "Porto", country: "PT", rank: 80 },
  { name: "Prague", country: "CZ", rank: 90 },
  { name: "Quebec City", country: "CA", rank: 80 },
  { name: "Queenstown", country: "NZ", rank: 70 },
  { name: "Quito", country: "EC", rank: 75 },
  { name: "Reykjavik", country: "IS", rank: 80 },
  { name: "Rhodes", country: "GR", rank: 75 },
  { name: "Riga", country: "LV", rank: 75 },
  { name: "Rio de Janeiro", country: "BR", rank: 90 },
  { name: "Riyadh", country: "SA", rank: 85 },
  { name: "Rome", country: "IT", rank: 95 },
  { name: "Rotterdam", country: "NL", rank: 80 },
  { name: "Salvador", country: "BR", rank: 75 },
  { name: "San Diego", country: "US", rank: 85 },
  { name: "San Francisco", country: "US", rank: 90 },
  { name: "San Jose", country: "CR", rank: 75 },
  { name: "San Juan", country: "PR", rank: 75 },
  { name: "Santa Fe", country: "US", rank: 70 },
  { name: "Santiago", country: "CL", rank: 85 },
  { name: "Sao Paulo", country: "BR", rank: 90 },
  { name: "Seattle", country: "US", rank: 85 },
  { name: "Seoul", country: "KR", rank: 90 },
  { name: "Seville", country: "ES", rank: 80 },
  { name: "Shanghai", country: "CN", rank: 95 },
  { name: "Shenzhen", country: "CN", rank: 85 },
  { name: "Singapore", country: "SG", rank: 95 },
  { name: "Sofia", country: "BG", rank: 75 },
  { name: "St. Petersburg", country: "RU", rank: 85 },
  { name: "Stockholm", country: "SE", rank: 90 },
  { name: "Sydney", country: "AU", rank: 95 },
  { name: "Taipei", country: "TW", rank: 85 },
  { name: "Tallinn", country: "EE", rank: 75 },
  { name: "Tampa", country: "US", rank: 75 },
  { name: "Tel Aviv", country: "IL", rank: 85 },
  { name: "Thessaloniki", country: "GR", rank: 75 },
  { name: "Tokyo", country: "JP", rank: 100 },
  { name: "Toronto", country: "CA", rank: 90 },
  { name: "Valencia", country: "ES", rank: 80 },
  { name: "Vancouver", country: "CA", rank: 90 },
  { name: "Venice", country: "IT", rank: 85 },
  { name: "Vienna", country: "AT", rank: 90 },
  { name: "Vilnius", country: "LT", rank: 75 },
  { name: "Warsaw", country: "PL", rank: 85 },
  { name: "Washington D.C.", country: "US", rank: 90 },
  { name: "Wellington", country: "NZ", rank: 80 },
  { name: "Zurich", country: "CH", rank: 90 },
];
